import importlib
import importlib.util
from pathlib import Path

from alembic.autogenerate import produce_migrations
from alembic.migration import MigrationContext
from alembic.operations import Operations
from config import *
import dbpool
from event import event
from kernel import *
from logger import *
from sqlalchemy import MetaData


class Event(event):

   def __init__(self):
      super().__init__()

   def run(self):
      logger.info("Starting automatic database schema discovery and update")

      # 1. Discover all base paths from MOD_PATH config
      modpath_str = config.get("GLOBAL", {}).get("MOD_PATH", "")
      base_dir = config["GLOBAL"]["BASE_DIR"]

      raw_paths = [p.strip() for p in modpath_str.split(":") if p.strip()]
      mod_dirs = []
      for p in raw_paths:
         mod_dirs.append(Path(p) if p.startswith("/") else Path(base_dir) / p)

      section_metadata_map = {}

      for mod_dir in mod_dirs:
         for dbdict_dir in mod_dir.glob("mod/*/dbDict"):
            if not dbdict_dir.is_dir():
               continue

            for section_dir in dbdict_dir.iterdir():
               if not section_dir.is_dir():
                  continue
               section_name = section_dir.name

               if section_name not in section_metadata_map:
                  section_metadata_map[section_name] = MetaData()

               target_metadata = section_metadata_map[section_name]
               for schema_file in section_dir.glob("*.py"):
                  if schema_file.name.startswith("__"):
                     continue
                  self._load_schema_file(
                     schema_file, section_name, target_metadata
                  )

      logger.info(
         f"Discovered schema sections: {list(section_metadata_map.keys())}"
      )

      for section_name, metadata in section_metadata_map.items():
         if not metadata.tables:
            logger.warning(
               f"No tables registered for section '{section_name}', skipping."
            )
            continue

         logger.info(
            f"--- Processing database update for section: '{section_name}' ---"
         )

         try:
            engine = dbpool.get_engine(section_name)
            self._alembic_sync_schema(engine, metadata)
            logger.info(
               f"Completed schema sync for section '{section_name}' ({len(metadata.tables)} tables registered)"
            )

         except Exception as e:
            logger.error(
               f"Failed to process database update for section '{section_name}': {e}",
               exc_info=True,
            )

      return {"status": "success", "exitcode": 0}

   def _load_schema_file(
      self, schema_file: Path, section_name: str, metadata: MetaData
   ):
      mod_name = f"dyn_dbdict_{section_name}_{schema_file.stem}"
      try:
         spec = importlib.util.spec_from_file_location(mod_name, schema_file)
         if spec and spec.loader:
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)

            if hasattr(mod, "get_table_schema"):
               mod.get_table_schema(metadata)
               logger.debug(
                  f"[{section_name}] Registered schema from {schema_file.name}"
               )
            else:
               logger.warning(
                  f"Schema file {schema_file} has no get_table_schema() function"
               )
      except Exception as e:
         logger.error(
            f"Error loading schema file {schema_file} for section '{section_name}': {e}"
         )

   def _alembic_sync_schema(self, engine, metadata: MetaData):
      """Uses Alembic to inspect, create missing tables/columns, and update column types/lengths."""
      with engine.begin() as conn:
         context = MigrationContext.configure(
            connection=conn,
            opts={
               "compare_type": True,
               "compare_server_default": True,
            },
         )

         # Inspect difference between DB and target metadata
         migration_script = produce_migrations(context, metadata)
         upgrade_ops = migration_script.upgrade_ops

         if upgrade_ops.is_empty():
            logger.info("Database schema is already up-to-date.")
            return

         logger.info("Applying schema modifications via Alembic...")
         op = Operations(context)

         # Apply autogenerated migrations directly
         for script_op in upgrade_ops.ops:
            op.invoke(script_op)